### ISSUE TITLE
[SUGGESTION] support cotton resources

### ISSUE THREAD

**Issue by Linguardium** [Snakefangox/modfest2022#1]
currently worldgen of ores are hardcoded. I would like to see a config option for this so that i can use cotton resources to control my worldgen rather than having mechanized copper ore and zinc ore, tech reborn ores, and any other ore adding mod.

i prefer centralized world gen when possible. even better if your hardcoded worldgen would disable if cotton resources is present and tell cotton resources it wants zinc and copper via datapack :)

**Comment by snakefangox** [comment]
That's absolutely something I should have done sooner. Let me see what I can do.

**Comment by snakefangox** [comment]
Mechanized will now switch off it's ore gen when Cotton Resources is installed and request oregen from there.
