### ISSUE TITLE
build from source, missing LoginMixin

### ISSUE THREAD

**Issue by Linguardium** [Snakefangox/modfest2022#2]
as of cd70551 LoginMixin was removed (gitignored) but is still in the mixin config (and the released version)

...are you doing something on player login that is being hidden?

**Comment by snakefangox** [comment]
Oh I screwed up with my git client, one sec.

**Comment by Linguardium** [comment]
no worries, just a little concerning with the PlusTic drama

**Comment by snakefangox** [comment]
Yeah, that's understandable.

**Comment by snakefangox** [comment]
Latest commit includes the LoginMixin.
