### ISSUE TITLE
Placing a boiler crashes the game

### ISSUE THREAD

**Issue by FaultyPixel** [Snakefangox/modfest2022#3]
Crash report : https://pastebin.com/aVhN5F5D
Also, I had a world with contraption from Mechanized already placed and working and now i get a crash on launch too. I will try and pin down wich mod is causing trouble (maybe Tech Reborn or Simple BC Pipes) and post an update here

**Comment by snakefangox** [comment]
Thanks for letting me know, I've had a poke around but I can't get it to crash on my end. Does it only crash on the server for you?

**Comment by FaultyPixel** [comment]
I'm not sure i understand what you are asking but i am running it on singleplayer. 
If i can provide you with more info just let me know what you need ! I'm currently trying Mechanized against every mod one by one to see what is causing the issue
Edit : Found the culprit ! I apologize for misleading you, it was neither Tech Reborn or Simple Pipes but Time Travel Mod. I don't understand mods enough to know if the issue comes from Mechanized or Time Travel so if i should just post the issue on their github please let me know !
Crash report : https://pastebin.com/wn0HHj8e

**Comment by snakefangox** [comment]
Thank you, I'll have a look, fix it if I can on my end and open an issue if not.

**Comment by snakefangox** [comment]
The issue occurs without Mechanized installed, seems the time travel mod is crashing whenever anyone tries to do anything with fluids using lib block attributes. I've opened an issue on their GitHub and linked back to here. Unfortunately I don't think there's anything else I can do on my end.
