### ISSUE TITLE
Failure to launch Version 1.7.0

### ISSUE THREAD

**Issue by Dragonracer1973** [Snakefangox/modfest2022#6]
[crash and bug reports.zip](https://github.com/Snakefangox/Mechanized/files/4531970/crash.and.bug.reports.zip)

**Comment by Dragonracer1973** [comment]
included are snip of launcher text, as well as log

**Comment by snakefangox** [comment]
Updating fabric API should fix this, let me know if it doesn't.

**Comment by Dragonracer1973** [comment]
console crash this time 
[process exit with code -1.zip](https://github.com/Snakefangox/Mechanized/files/4532022/process.exit.with.code.-1.zip)

**Comment by snakefangox** [comment]
Ah, looks like Corail Woodcutter doesn't support the latest version of fabric API. That's a pain. Don't think there's anything I can do about that on my end, sorry. Mechanized 1.6.0 should work with the older version of fabric api.

**Comment by Dragonracer1973** [comment]
yeah I am going to fall back for now and file an Issue with corail, also I needed to update my libblockattributes, alsoalso thanks for the help
