### ISSUE TITLE
1.15.2 Pipe rendering bug

### ISSUE THREAD

**Issue by inklesspen1rus** [Snakefangox/modfest2022#8]
Step 1:
![image](https://user-images.githubusercontent.com/22255205/80959928-7c0bf200-8e10-11ea-9d0c-fd12b5aaf163.png)
Step 2:
![image](https://user-images.githubusercontent.com/22255205/80959968-8f1ec200-8e10-11ea-82ba-c43fcf467d2a.png)
Step 3:
![image](https://user-images.githubusercontent.com/22255205/80959978-9514a300-8e10-11ea-9204-4d844d64022e.png)

Where is connection?
![image](https://user-images.githubusercontent.com/22255205/80959992-9d6cde00-8e10-11ea-95c9-2dac14438a9d.png)

Mechanized version is 1.7.0
Playing with optifine

**Comment by snakefangox** [comment]
Huh, thanks for the report I'll look into this as soon as I can.

**Comment by snakefangox** [comment]
Should be fixed in 1.8.0
