### ISSUE TITLE
1.15.2 Steam Fraction Tower breaks bedrock?

### ISSUE THREAD

**Issue by inklesspen1rus** [Snakefangox/modfest2022#9]
Mechanized version is 1.7.0
Just look at this
![image](https://user-images.githubusercontent.com/22255205/80960721-1456a680-8e12-11ea-8ff0-8258e66678dc.png)
Is it normal?

**Comment by snakefangox** [comment]
Ah, that is not intended. I think it only happens on super flat worlds but regardless I need to fix that.

**Comment by snakefangox** [comment]
Sorry for the wait, version 1.8.0 should fix this.
